
one_at_a_time: False
images:
    - "TestTargets_originals/-5x15_0deg.jpg"
    - "TestTargets_originals/-5x20_0deg.jpg"
    - "TestTargets_originals/-5x5_0deg.jpg"
    - "TestTargets_originals/0x10_0deg.jpg"
    - "TestTargets_originals/0x10_15deg.jpg"
    - "TestTargets_originals/0x10_30deg.jpg"
    - "TestTargets_originals/0x10_45.jpg"
    - "TestTargets_originals/0x15_0deg.jpg"
    - "TestTargets_originals/0x15_15.jpg"
    - "TestTargets_originals/0x15_30.jpg"
    - "TestTargets_originals/0x15_45.jpg"
    - "TestTargets_originals/0x20_0deg.jpg"
    - "TestTargets_originals/0x5_0deg.jpg"
    - "TestTargets_originals/0x5_15deg.jpg"
    - "TestTargets_originals/0x5_30deg.jpg"
    - "TestTargets_originals/0x5_45deg.jpg"
    - "TestTargets_originals/20161027_194658.jpg"
    - "TestTargets_originals/20161027_195254.jpg"
    - "TestTargets_originals/20161027_195630.jpg"
    - "TestTargets_originals/20161027_200255.jpg"
    - "TestTargets_originals/20161027_200500.jpg"
    - "TestTargets_originals/20161027_202427.jpg"
    - "TestTargets_originals/20161027_202441.jpg"
    - "TestTargets_originals/20161027_202611.jpg"
    - "TestTargets_originals/20161027_202731.jpg"
    - "TestTargets_originals/20161027_202739.jpg"
    - "TestTargets_originals/5x10_0deg.jpg"
    - "TestTargets_originals/5x10_15.jpg"
    - "TestTargets_originals/5x10_30.jpg"
    - "TestTargets_originals/5x15_0deg.jpg"
    - "TestTargets_originals/5x15_15.jpg"
    - "TestTargets_originals/5x15_30.jpg"
    - "TestTargets_originals/5x15_45.jpg"
    - "TestTargets_originals/5x20_0deg.jpg"
    - "TestTargets_originals/5x5_0deg.jpg"
    - "TestTargets_originals/5x5_15.jpg"
    - "TestTargets_originals/5x5_30.jpg"
    - "TestTargets_originals/5x5_45.jpg"
    - "TestTargets_originals/ground_5x10.jpg"
    - "TestTargets_originals/ground_5x15.jpg"